### ISSUE TITLE
Create DJango Version

### ISSUE THREAD

**Issue by Negative-light** [DanPace725/4T-TalkToTikTok#3]
Django is a web framework that would allow this to possibly work well for a self-hosted solution.

**Comment by DanPace725** [comment]
Using a virtual environment is a best practice when working with Python projects as it helps to manage dependencies and avoid conflicts. Here's how you can integrate virtual environment setup into the instructions:

### Django Setup Instructions for 4T-TalkToTikTok with Virtual Environment:

1. **Clone the Repository**:
   ```
   git clone https://github.com/DanPace725/4T-TalkToTikTok.git
   ```

2. **Navigate to the Project Directory**:
   ```
   cd 4T-TalkToTikTok
   ```

3. **Set Up a Virtual Environment**:
   First, you'll need to install `virtualenv` if you haven't already:
   ```
   pip install virtualenv
   ```
   Then, create a new virtual environment:
   ```
   virtualenv venv
   ```

4. **Activate the Virtual Environment**:
   - On macOS and Linux:
     ```
     source venv/bin/activate
     ```
   - On Windows:
     ```
     .\venv\Scripts\activate
     ```

5. **Install the Required Dependencies**:
   With the virtual environment activated, install the necessary Python packages:
   ```
   pip install -r requirements.txt
   ```

6. **Set Up Environment Variables**:
   The `settings.py` file indicates that the OpenAI API key is fetched from an environment variable. You'll need to set this up:
   ```
   export OPENAI_API_KEY='your_openai_api_key_here'
   ```

7. **Database Setup**:
   The project uses SQLite as its database. To set up the database and apply migrations, run:
   ```
   python T2TT/manage.py migrate
   ```

8. **Run the Django Development Server**:
   ```
   python T2TT/manage.py runserver
   ```

9. **Access the Application**:
   Once the server is running, you can access the application by navigating to `http://127.0.0.1:8000/` in your browser.

10. **URLs**:
   - The main page can be accessed at the root URL (`/`).
   - The download and transcribe view is available at `/download/`.
   - The success page can be accessed at `/success/`.

11. **Media Files**:
   The `settings.py` file indicates that media files (like uploaded videos and audio) are stored in a `media` directory in the project root. Ensure that this directory has the appropriate permissions for file storage.

12. **Additional Configuration**:
   - Ensure you have `ffmpeg` installed and accessible from the command line for video to audio conversion.
   - The project uses the `pyktok` library for downloading TikTok videos. Ensure you have the necessary dependencies and configurations for this library.

13. **Admin Panel**:
   Django comes with a built-in admin panel. You can access it at `/admin/`. To use it, you'll first need to create a superuser:
   ```
   python T2TT/manage.py createsuperuser
   ```

14. **Deactivate the Virtual Environment**:
   Once you're done working on the project, you can deactivate the virtual environment:
   ```
   deactivate
   ```

By following these steps, you'll have the Django project set up within a virtual environment, ensuring that all dependencies are isolated from your global Python environment.
